# -*- coding: utf-8 -*-
"""Sales Forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx1JxkW-53nmEEIgelWH_cNl4hiUmRFg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
df = pd.read_excel("/content/sales_forecasting.xlsx")

# Convert date
df['date'] = pd.to_datetime(df['date'])

# Sort by date
df = df.sort_values('date')

df.head()

daily_sales = df.groupby('date')['total_sales'].sum()

daily_sales.head()

plt.figure(figsize=(10,5))
plt.plot(daily_sales)
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.show()

decomposition = seasonal_decompose(daily_sales, model='additive', period=30)

decomposition.plot()
plt.show()

train = daily_sales[:-30]   # last 30 days test
test = daily_sales[-30:]

model = ARIMA(train, order=(1,1,1))
model_fit = model.fit()

forecast = model_fit.forecast(steps=30)

plt.figure(figsize=(10,5))
plt.plot(train.index, train, label="Training Data")
plt.plot(test.index, test, label="Actual Sales")
plt.plot(test.index, forecast, label="Forecasted Sales", linestyle="--")
plt.title("Sales Forecast vs Actual")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.legend()
plt.show()

mae = mean_absolute_error(test, forecast)
rmse = np.sqrt(mean_squared_error(test, forecast))

mae, rmse









